"""posts table

Revision ID: e60f931c39d9
Revises: 8dc9acd5828e
Create Date: 2020-04-02 01:26:09.649548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60f931c39d9'
down_revision = '8dc9acd5828e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_author', table_name='post')
    op.drop_column('post', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.VARCHAR(length=120), nullable=True))
    op.create_index('ix_post_author', 'post', ['author'], unique=False)
    # ### end Alembic commands ###
